// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bioracclqflukclophsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpb3JhY2NscWZsdWtjbG9waHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjI3MjcsImV4cCI6MjA3NDIzODcyN30.MqxV0qVjOa-3hlUavipOAgDpswrg2px8jpDJdCr2s24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);